### ISSUE TITLE
[Solved] Encoding problem

### ISSUE THREAD

**Issue by hurbawoo** [genotrance/fru-tool#14]
I installed FRU Tool on Windows.
frutool works fine, but 'generate' fails with cp949.
![image](https://github.com/genotrance/fru-tool/assets/14929274/df793654-9460-4e34-a61e-3a5e8a35388d)

After some research, I modified the **toml_format.py** and fixed it.
![image](https://github.com/genotrance/fru-tool/assets/14929274/bc797ccb-6d69-4c3f-9769-2a6d17cc77e2)

Thank you

**Comment by kurtmckee** [comment]
I thought that UTF-8 was the default. Turns out it's platform-dependent. Thanks for reporting this!
